---
- hosts: swarm-manager
  become: false
  roles:
  - docker-undeploy
　
# host_vars folder has the vaulted sudo password file for each swarm worker.
# # Here, sudo is set at host level. It can be set at roles level as well as at tasks level.
- hosts: swarm-worker
  become: yes
  become_user: root
  roles:
  - docker-undeploy
　
# host_vars folder has the vaulted sudo password file for each swarm worker.
# # # Here, sudo is set at host level. It can be set at roles level as well as at tasks level.
- hosts: hdfs-*
  become: yes
  become_user: root
  roles:
  - docker-undeploy
　
